### ISSUE TITLE
Rust port

### ISSUE THREAD

**Issue by nem0** [mizquierdo97/Engine#2]
Did you consider rewriting it in Rust?

**Comment by Alan-FGR** [comment]
@nem0 why would they rewrite in Rust if they can rewrite in C#?

**Comment by nem0** [comment]
C# is outdated, Rust is much better.

**Comment by Alan-FGR** [comment]
Not true! Rust sucks! :rage4:

**Comment by nem0** [comment]
Do you have ```friend```s in c#?

**Comment by Alan-FGR** [comment]
Nope, but who needs friends anyway?

**Comment by nem0** [comment]
Nah, look at https://github.com/Alan-FGR/aelum it's in C# and it sucks

**Comment by Alan-FGR** [comment]
Says the guy with a [C# plugin in the works](https://github.com/nem0/lumixengine_csharp) for his engine

**Comment by mizquierdo97** [comment]
This is a college project, so no for now :)

**Comment by nem0** [comment]
pity, I hoped you are hipster enough :trollface:
