### ISSUE TITLE
C# Port

### ISSUE THREAD

**Issue by Alan-FGR** [mizquierdo97/Engine#3]
Did you consider rewriting it in C#?

**Comment by Alan-FGR** [comment]
@nem0 see how the C# port is still being considered while the Rust one was immediately dismissed? I think we have a winner :)

**Comment by nem0** [comment]
Nope, they do not even bother to reply. And I closed the Rust issue

**Comment by Alan-FGR** [comment]
Bullshit! You're just a sore loser!

**Comment by Alan-FGR** [comment]
![image](https://user-images.githubusercontent.com/8399299/32392425-c9fe6250-c0bc-11e7-87d5-9fe9f7c04755.png)

**Comment by nem0** [comment]
![image](https://user-images.githubusercontent.com/153526/32392480-364bece8-c0d6-11e7-8112-7c4eab91fe16.png)

**Comment by Alan-FGR** [comment]
yours is so obviously an image because it gets scaled... total fail 😆

**Comment by nem0** [comment]
ofc, it's screenshot of what you said

**Comment by Alan-FGR** [comment]
right... *right*... :trollface:
